"""Ford lateral-control extensions.

The extended curvature strategy, manual-turn detector, and related safety protocol are substantially
adapted from BluePilot's Ford work, principally by Alan Polk and additional contributors. The audited
bp-7.0 reference is e1d051d7ba270261b4455068bd68f1a58db15a4a; source attribution is retained in
CREDITS.md and THIRD_PARTY_NOTICES.md. StarPilot reorganized that work for its own architecture and has since
changed its tuning and lookahead behavior.

See CREDITS.md for feature-level authorship and upstream commits, and THIRD_PARTY_NOTICES.md for the
published upstream license notices. Upstream contributors do not maintain this adaptation.

Mach-E admission and modern command envelope; pure strategy is shared separately.
"""

from dataclasses import replace

import numpy as np

from opendbc.car import structs
from opendbc.car.ford.values import CAR, FordFlags, FordSafetyFlags
from opendbc.car.lateral import MAX_LATERAL_JERK
from opendbc.car.ford.lateral_strategy import (
  FordLateralController,
  FORD_CURVATURE_LIMITS as FORD_CURVATURE_LIMITS,
  MAX_LATERAL_ACCEL as MAX_LATERAL_ACCEL,
  STEER_DT as STEER_DT,
  CURVATURE_LOOKAHEAD_MIN as CURVATURE_LOOKAHEAD_MIN,
  CURVATURE_LOOKAHEAD_MAX as CURVATURE_LOOKAHEAD_MAX,
  MACH_E_TURN_IN_LOOKAHEAD_EXTRA as MACH_E_TURN_IN_LOOKAHEAD_EXTRA,
  MACH_E_LOW_SPEED_TURN_IN_LOOKAHEAD_EXTRA as MACH_E_LOW_SPEED_TURN_IN_LOOKAHEAD_EXTRA,
  MACH_E_LOW_SPEED_TURN_IN_START_SPEED as MACH_E_LOW_SPEED_TURN_IN_START_SPEED,
  MACH_E_LOW_SPEED_TURN_IN_FULL_SPEED as MACH_E_LOW_SPEED_TURN_IN_FULL_SPEED,
  MACH_E_LOW_SPEED_TURN_IN_MAX_SPEED as MACH_E_LOW_SPEED_TURN_IN_MAX_SPEED,
  MACH_E_LOW_SPEED_TURN_IN_FADE_SPEED as MACH_E_LOW_SPEED_TURN_IN_FADE_SPEED,
  MACH_E_TURN_IN_MIN_CURVATURE as MACH_E_TURN_IN_MIN_CURVATURE,
  MACH_E_TURN_IN_FULL_CURVATURE as MACH_E_TURN_IN_FULL_CURVATURE,
  MACH_E_TURN_IN_LAG_CURVATURE as MACH_E_TURN_IN_LAG_CURVATURE,
  MACH_E_UNWIND_LOOKAHEAD_EXTRA as MACH_E_UNWIND_LOOKAHEAD_EXTRA,
  MACH_E_UNWIND_FULL_LAG_CURVATURE as MACH_E_UNWIND_FULL_LAG_CURVATURE,
  MACH_E_UNWIND_PREVIEW_LAG_CURVATURE as MACH_E_UNWIND_PREVIEW_LAG_CURVATURE,
  MACH_E_DIRECTION_CHANGE_MIN_SPEED as MACH_E_DIRECTION_CHANGE_MIN_SPEED,
  MACH_E_DIRECTION_CHANGE_LOOKAHEAD_RAMP_SPEED as MACH_E_DIRECTION_CHANGE_LOOKAHEAD_RAMP_SPEED,
  MACH_E_DIRECTION_CHANGE_LOOKAHEAD_FULL_SPEED as MACH_E_DIRECTION_CHANGE_LOOKAHEAD_FULL_SPEED,
  MACH_E_DIRECTION_CHANGE_LOOKAHEAD_FADE_SPEED as MACH_E_DIRECTION_CHANGE_LOOKAHEAD_FADE_SPEED,
  MACH_E_DIRECTION_CHANGE_LOOKAHEAD_EXTRA as MACH_E_DIRECTION_CHANGE_LOOKAHEAD_EXTRA,
  MACH_E_DIRECTION_CHANGE_MIN_PREVIEW_CURVATURE as MACH_E_DIRECTION_CHANGE_MIN_PREVIEW_CURVATURE,
  MACH_E_DIRECTION_CHANGE_FULL_PREVIEW_CURVATURE as MACH_E_DIRECTION_CHANGE_FULL_PREVIEW_CURVATURE,
  MACH_E_DIRECTION_CHANGE_MIN_LAG_CURVATURE as MACH_E_DIRECTION_CHANGE_MIN_LAG_CURVATURE,
  MACH_E_DIRECTION_CHANGE_FULL_LAG_CURVATURE as MACH_E_DIRECTION_CHANGE_FULL_LAG_CURVATURE,
  MACH_E_DIRECTION_CHANGE_EARLY_MIN_LAG_CURVATURE as MACH_E_DIRECTION_CHANGE_EARLY_MIN_LAG_CURVATURE,
  MACH_E_DIRECTION_CHANGE_EARLY_FULL_LAG_CURVATURE as MACH_E_DIRECTION_CHANGE_EARLY_FULL_LAG_CURVATURE,
  MACH_E_DIRECTION_CHANGE_EARLY_MIN_CURVATURE as MACH_E_DIRECTION_CHANGE_EARLY_MIN_CURVATURE,
  MACH_E_DIRECTION_CHANGE_EARLY_FULL_CURVATURE as MACH_E_DIRECTION_CHANGE_EARLY_FULL_CURVATURE,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_START_SPEED as MACH_E_LOW_SPEED_DIRECTION_CHANGE_START_SPEED,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_FULL_SPEED as MACH_E_LOW_SPEED_DIRECTION_CHANGE_FULL_SPEED,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_HOLD_SPEED as MACH_E_LOW_SPEED_DIRECTION_CHANGE_HOLD_SPEED,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_FADE_SPEED as MACH_E_LOW_SPEED_DIRECTION_CHANGE_FADE_SPEED,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_MIN_CURVATURE as MACH_E_LOW_SPEED_DIRECTION_CHANGE_MIN_CURVATURE,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_FULL_CURVATURE as MACH_E_LOW_SPEED_DIRECTION_CHANGE_FULL_CURVATURE,
  MACH_E_LOW_SPEED_DIRECTION_CHANGE_MAX_CURVATURE as MACH_E_LOW_SPEED_DIRECTION_CHANGE_MAX_CURVATURE,
  MACH_E_SHARP_DIRECTION_CHANGE_START_SPEED as MACH_E_SHARP_DIRECTION_CHANGE_START_SPEED,
  MACH_E_SHARP_DIRECTION_CHANGE_FULL_SPEED as MACH_E_SHARP_DIRECTION_CHANGE_FULL_SPEED,
  MACH_E_SHARP_DIRECTION_CHANGE_HOLD_SPEED as MACH_E_SHARP_DIRECTION_CHANGE_HOLD_SPEED,
  MACH_E_SHARP_DIRECTION_CHANGE_FADE_SPEED as MACH_E_SHARP_DIRECTION_CHANGE_FADE_SPEED,
  MACH_E_SHARP_DIRECTION_CHANGE_MIN_CURVATURE as MACH_E_SHARP_DIRECTION_CHANGE_MIN_CURVATURE,
  MACH_E_SHARP_DIRECTION_CHANGE_FULL_CURVATURE as MACH_E_SHARP_DIRECTION_CHANGE_FULL_CURVATURE,
  MACH_E_SHARP_DIRECTION_CHANGE_MIN_PREVIEW_CURVATURE as MACH_E_SHARP_DIRECTION_CHANGE_MIN_PREVIEW_CURVATURE,
  MACH_E_SHARP_DIRECTION_CHANGE_FULL_PREVIEW_CURVATURE as MACH_E_SHARP_DIRECTION_CHANGE_FULL_PREVIEW_CURVATURE,
  MACH_E_SHARP_DIRECTION_CHANGE_MIN_ACCEL as MACH_E_SHARP_DIRECTION_CHANGE_MIN_ACCEL,
  MACH_E_SHARP_DIRECTION_CHANGE_FULL_ACCEL as MACH_E_SHARP_DIRECTION_CHANGE_FULL_ACCEL,
  MACH_E_SHARP_DIRECTION_CHANGE_MIN_LAG_CURVATURE as MACH_E_SHARP_DIRECTION_CHANGE_MIN_LAG_CURVATURE,
  MACH_E_SHARP_DIRECTION_CHANGE_FULL_LAG_CURVATURE as MACH_E_SHARP_DIRECTION_CHANGE_FULL_LAG_CURVATURE,
  MACH_E_CURVATURE_ERROR_MAX as MACH_E_CURVATURE_ERROR_MAX,
  MACH_E_UNDERSTEER_ERROR_MIN_DEFICIT as MACH_E_UNDERSTEER_ERROR_MIN_DEFICIT,
  MACH_E_UNDERSTEER_ERROR_FULL_DEFICIT as MACH_E_UNDERSTEER_ERROR_FULL_DEFICIT,
  MACH_E_PATH_ANGLE_MAX as MACH_E_PATH_ANGLE_MAX,
  MACH_E_PATH_ANGLE_STEP as MACH_E_PATH_ANGLE_STEP,
  MACH_E_PATH_ANGLE_FADE_START_SPEED as MACH_E_PATH_ANGLE_FADE_START_SPEED,
  MACH_E_PATH_ANGLE_MAX_SPEED as MACH_E_PATH_ANGLE_MAX_SPEED,
  MACH_E_PATH_ANGLE_TRACKING_FACTOR as MACH_E_PATH_ANGLE_TRACKING_FACTOR,
  MACH_E_PATH_ANGLE_DRIVER_COOLDOWN as MACH_E_PATH_ANGLE_DRIVER_COOLDOWN,
  MACH_E_DRIVER_ASSIST_MIN_SPEED as MACH_E_DRIVER_ASSIST_MIN_SPEED,
  MACH_E_DRIVER_ASSIST_MAX_SPEED as MACH_E_DRIVER_ASSIST_MAX_SPEED,
  MACH_E_DRIVER_ASSIST_MAX_TORQUE as MACH_E_DRIVER_ASSIST_MAX_TORQUE,
  FORD_CURVATURE_LOOKAHEAD as FORD_CURVATURE_LOOKAHEAD,
  FORD_CONSERVATIVE_PREVIEW_CARS as FORD_CONSERVATIVE_PREVIEW_CARS,
  FORD_SHARP_DIRECTION_CHANGE_CARS as FORD_SHARP_DIRECTION_CHANGE_CARS,
  FORD_MANUAL_TURN_LATCH_CARS as FORD_MANUAL_TURN_LATCH_CARS,
  MANUAL_TURN_ENTRY_ANGLE_DEG as MANUAL_TURN_ENTRY_ANGLE_DEG,
  MANUAL_TURN_RELEASE_ANGLE_DEG as MANUAL_TURN_RELEASE_ANGLE_DEG,
  MANUAL_TURN_RECOVERY_SECONDS as MANUAL_TURN_RECOVERY_SECONDS,
  FordLateralResult as FordLateralResult,
  HumanTurnDetector as HumanTurnDetector,
)


class MachELateralController(FordLateralController):
  """Compatibility owner for the exact admitted Mach-E profile."""


def qualified(CP) -> bool:
  if (CP.brand != "ford" or CP.carFingerprint != CAR.FORD_MUSTANG_MACH_E_MK1 or
      not CP.flags & FordFlags.CANFD or CP.flags & ~int(FordFlags.CANFD | FordFlags.HAS_BSM) or
      CP.passive or CP.dashcamOnly or CP.notCar or CP.alternativeExperience != 0 or
      len(CP.safetyConfigs) not in (1, 2)):
    return False
  if len(CP.safetyConfigs) == 2 and (CP.safetyConfigs[0].safetyModel != structs.CarParams.SafetyModel.noOutput or
                                     CP.safetyConfigs[0].safetyParam != 0):
    return False
  safety = CP.safetyConfigs[-1]
  return (safety.safetyModel == structs.CarParams.SafetyModel.ford and
          safety.safetyParam == int(FordSafetyFlags.CANFD | FordSafetyFlags.MACH_E_EXTENDED |
                                    (FordSafetyFlags.LONG_CONTROL if CP.openpilotLongitudinalControl else 0)))


def bounded_command(owner: MachELateralController, demanded: FordLateralResult, previous: float, speed: float,
                    previous_path_angle: float = 0.0) -> FordLateralResult:
  """Intersect original demand with modern transient limits and old absolute cap.

  A discontinuous speed change may leave no legal active interval. Withdraw the
  request then, rather than clipping outside the jerk interval. Histories always
  follow emitted fields; the original demand remains observable separately.
  """
  cap = min(0.02, MAX_LATERAL_ACCEL / max(speed, 1.0) ** 2)
  jerk_delta = MAX_LATERAL_JERK / max(speed, 1.0) ** 2 * STEER_DT
  low, high = max(-cap, previous - jerk_delta), min(cap, previous + jerk_delta)
  if not demanded.active or low > high:
    command = FordLateralResult()
  else:
    curvature = float(np.clip(demanded.curvature, low, high))
    path_angle = 0.0
    if (3.0 <= speed < MACH_E_PATH_ANGLE_MAX_SPEED and abs(curvature) >= 0.0195 and
        curvature * demanded.path_angle > 0.0):
      headroom = max(0.0, (MAX_LATERAL_ACCEL / speed ** 2 - abs(curvature)) * speed)
      path_cap = min(MACH_E_PATH_ANGLE_MAX, headroom)
      path_low = max(-path_cap, previous_path_angle - MACH_E_PATH_ANGLE_STEP)
      path_high = min(path_cap, previous_path_angle + MACH_E_PATH_ANGLE_STEP)
      if path_low <= path_high:
        path_angle = float(np.clip(demanded.path_angle, path_low, path_high))
        if path_angle * curvature <= 0.0:
          path_angle = 0.0
    command = replace(demanded, curvature=curvature, path_angle=path_angle)
  owner.curvature_last = command.curvature
  owner.path_angle_last = command.path_angle
  return command
