#pragma once

#include <string>
#include <unordered_map>

#include "openpilot/cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT, BOOL}},
    {"BluetoothEnabled", {PERSISTENT, BOOL}},
    {"DisableOpenpilotLongitudinal", {PERSISTENT, BOOL, "0"}},
    {"AlwaysOnDM", {PERSISTENT, BOOL}},
    {"WarningImmediateVolume", {PERSISTENT, INT}},
    {"WarningSoftVolume", {PERSISTENT, INT}},
    {"RefuseVolume", {PERSISTENT, INT}},
    {"PromptDistractedVolume", {PERSISTENT, INT}},
    {"SoundPack", {PERSISTENT, STRING, "starpilot"}},
    {"EngageVolume", {PERSISTENT, INT}},
    {"DisengageVolume", {PERSISTENT, INT}},
    {"PromptVolume", {PERSISTENT, INT}},
    {"AlwaysOnLateral", {PERSISTENT, BOOL, "0"}},
    {"NostalgiaMode", {PERSISTENT, BOOL, "0"}},
    {"ToyotaAutoHold", {PERSISTENT, BOOL, "0"}},
    {"FordHumanTurnDetection", {PERSISTENT, BOOL, "1"}},
    {"OnroadCustomizations", {PERSISTENT | DONT_LOG, JSON}},
    {"StarPilotFavoriteSlots", {PERSISTENT, JSON, R"([{"enabled":false,"show_onroad":false,"key":null,"label":""},{"enabled":false,"show_onroad":false,"key":null,"label":""},{"enabled":false,"show_onroad":false,"key":null,"label":""}])"}},
    {"StarPilotControllerBindings", {PERSISTENT | DONT_LOG, JSON}},
    {"UseStarPilotLongitudinalPlanner", {PERSISTENT, BOOL, "1"}},
    {"CustomPersonalities", {PERSISTENT, BOOL, "0"}},
    {"SettingsRetirementState", {PERSISTENT | DONT_LOG, JSON}},
    {"RetiredSettingsEvidence", {PERSISTENT | DONT_LOG, JSON}},
    {"QOLLongitudinal", {PERSISTENT, BOOL}},
    {"ReverseCruise", {PERSISTENT, BOOL, "0"}},
    {"ForceStops", {PERSISTENT, BOOL, "0"}},
    {"AlwaysAllowUploads", {PERSISTENT, BOOL, "0"}},
    {"ForceStopDistanceOffset", {PERSISTENT, INT, "0"}},
    {"LeadApproachBuffer", {PERSISTENT, BOOL, "0"}},
    {"FasterLeadTakeoff", {PERSISTENT, BOOL, "0"}},
    {"SwitchbackModeCooldown", {PERSISTENT, FLOAT, "5.0"}},
    {"CustomCruise", {PERSISTENT, FLOAT, "1.0"}},
    {"CustomCruiseLong", {PERSISTENT, FLOAT, "5.0"}},
    {"LongitudinalPersonalityProfiles", {PERSISTENT | DONT_LOG, JSON, "{}"}},
    {"TrafficPersonalityProfile", {PERSISTENT, BOOL}},
    {"AggressivePersonalityProfile", {PERSISTENT, BOOL}},
    {"StandardPersonalityProfile", {PERSISTENT, BOOL}},
    {"RelaxedPersonalityProfile", {PERSISTENT, BOOL}},
    {"TrafficFollow", {PERSISTENT, FLOAT, "0.75"}},
    {"AggressiveFollow", {PERSISTENT, FLOAT, "1.25"}},
    {"AggressiveFollowHigh", {PERSISTENT, FLOAT, "1.0"}},
    {"StandardFollow", {PERSISTENT, FLOAT, "1.45"}},
    {"StandardFollowHigh", {PERSISTENT, FLOAT, "1.2"}},
    {"RelaxedFollow", {PERSISTENT, FLOAT, "1.6"}},
    {"RelaxedFollowHigh", {PERSISTENT, FLOAT, "1.4"}},
    {"TrafficJerkAcceleration", {PERSISTENT, FLOAT, "100.0"}},
    {"TrafficJerkDeceleration", {PERSISTENT, FLOAT, "100.0"}},
    {"TrafficJerkDanger", {PERSISTENT, FLOAT, "100.0"}},
    {"TrafficJerkSpeed", {PERSISTENT, FLOAT, "100.0"}},
    {"TrafficJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0"}},
    {"AggressiveJerkAcceleration", {PERSISTENT, FLOAT, "50.0"}},
    {"AggressiveJerkDeceleration", {PERSISTENT, FLOAT, "50.0"}},
    {"AggressiveJerkDanger", {PERSISTENT, FLOAT, "100.0"}},
    {"AggressiveJerkSpeed", {PERSISTENT, FLOAT, "50.0"}},
    {"AggressiveJerkSpeedDecrease", {PERSISTENT, FLOAT, "50.0"}},
    {"StandardJerkAcceleration", {PERSISTENT, FLOAT, "100.0"}},
    {"StandardJerkDeceleration", {PERSISTENT, FLOAT, "100.0"}},
    {"StandardJerkDanger", {PERSISTENT, FLOAT, "100.0"}},
    {"StandardJerkSpeed", {PERSISTENT, FLOAT, "100.0"}},
    {"StandardJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0"}},
    {"RelaxedJerkAcceleration", {PERSISTENT, FLOAT, "100.0"}},
    {"RelaxedJerkDeceleration", {PERSISTENT, FLOAT, "100.0"}},
    {"RelaxedJerkDanger", {PERSISTENT, FLOAT, "100.0"}},
    {"RelaxedJerkSpeed", {PERSISTENT, FLOAT, "100.0"}},
    {"RelaxedJerkSpeedDecrease", {PERSISTENT, FLOAT, "100.0"}},
    {"PauseAOLOnBrake", {PERSISTENT, FLOAT, "0.0"}},
    {"AolBrakePauseSpeedMps", {PERSISTENT, FLOAT}},
    {"LaneCentering", {PERSISTENT, BOOL, "0"}},
    {"LaneCenteringPauseOnSignal", {PERSISTENT, BOOL, "1"}},
    {"LaneCenterOffset", {PERSISTENT, FLOAT, "0.0"}},
    {"LaneCenteringE2EAuthority", {PERSISTENT, FLOAT, "1.0"}},
    {"LaneCenteringStrength", {PERSISTENT, FLOAT, "1.0"}},
    {"AndroidAutoEnabled", {PERSISTENT | DONT_LOG, BOOL, "0"}},
    {"AdvancedLateralTune", {PERSISTENT, BOOL}},
    {"LateralControllerSelection", {PERSISTENT | DONT_LOG, JSON}},
    {"ForceAutoTuneOff", {PERSISTENT, BOOL, "0"}},
    {"SteerLatAccel", {PERSISTENT, FLOAT}},
    {"SteerLatAccelStock", {PERSISTENT, FLOAT}},
    {"SteerFriction", {PERSISTENT, FLOAT}},
    {"SteerFrictionStock", {PERSISTENT, FLOAT}},
    {"TorqueOverrideDocument", {PERSISTENT | DONT_LOG, JSON}},
    {"HideSpeed", {PERSISTENT, BOOL, "0"}},
    {"HideMaxSpeed", {PERSISTENT, BOOL, "0"}},
    {"HideSteeringWheel", {PERSISTENT, BOOL, "0"}},
    {"CameraView", {PERSISTENT, INT, "0"}},
    {"DriverCamera", {PERSISTENT, BOOL, "0"}},
    {"StoppedTimer", {PERSISTENT, BOOL, "0"}},
    {"StockConfidenceBallWidget", {PERSISTENT, BOOL, "0"}},
    {"EnableTorqueBarWidget", {PERSISTENT, BOOL, "1"}},
    {"HideLeadMarker", {PERSISTENT, BOOL, "1"}},
    {"LeadInfo", {PERSISTENT, BOOL, "0"}},
    {"LeadInfoMode", {PERSISTENT, INT, "2"}},
    {"BlindSpotMetrics", {PERSISTENT, BOOL, "1"}},
    {"SignalMetrics", {PERSISTENT, BOOL, "0"}},
    {"PIPPreviewEnabled", {PERSISTENT, BOOL, "0"}},
    {"PIPPreviewMask", {PERSISTENT | DONT_LOG, JSON, "{\"width\":1928,\"height\":1208,\"center_left\":[315,548],\"center_right\":[1571,539],\"crop_size\":580}"}},
    {"PIPPreviewShowOnBlinker", {PERSISTENT, BOOL, "0"}},
    {"PIPPreviewShowOnBSM", {PERSISTENT, BOOL, "0"}},
    {"PIPPreviewInvert", {PERSISTENT, BOOL, "0"}},
    {"StarPilotDisplayPreferencesEnabled", {PERSISTENT, BOOL}},
    {"ScreenBrightness", {PERSISTENT, INT}},
    {"ScreenBrightnessOnroad", {PERSISTENT, INT}},
    {"ScreenTimeout", {PERSISTENT, INT}},
    {"ScreenTimeoutOnroad", {PERSISTENT, INT}},
    {"LKASButtonControl", {PERSISTENT, INT, "0"}},
    {"MainCruiseButtonControl", {PERSISTENT, INT, "0"}},
    {"DistanceButtonControl", {PERSISTENT, INT, "0"}},
    {"LongDistanceButtonControl", {PERSISTENT, INT, "0"}},
    {"VeryLongDistanceButtonControl", {PERSISTENT, INT, "0"}},
    {"ModeButtonControl", {PERSISTENT, INT, "0"}},
    {"LongModeButtonControl", {PERSISTENT, INT, "0"}},
    {"VeryLongModeButtonControl", {PERSISTENT, INT, "0"}},
    {"StarButtonControl", {PERSISTENT, INT, "0"}},
    {"LongStarButtonControl", {PERSISTENT, INT, "0"}},
    {"VeryLongStarButtonControl", {PERSISTENT, INT, "0"}},
    {"CancelButtonControl", {PERSISTENT, INT, "0"}},
    {"LongCancelButtonControl", {PERSISTENT, INT, "0"}},
    {"VeryLongCancelButtonControl", {PERSISTENT, INT, "0"}},
    {"LongPitch", {PERSISTENT, BOOL, "1"}},
    {"LongitudinalMaxOutputAcceleration", {PERSISTENT, FLOAT, "4.0"}},
    {"TuningPreparationState", {PERSISTENT, JSON, ""}},
    {"TurnAssist", {PERSISTENT, BOOL, "0"}},
    {"GMPedalLongitudinal", {PERSISTENT, BOOL, "0"}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableDriverCameraIR", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT, BOOL}},
    {"DisableUpdates", {PERSISTENT, BOOL}},
    {"DisengageOnAccelerator", {PERSISTENT, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"DriverLockoutCount", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, INT, "0"}},
    {"AlphaLongitudinalEnabled", {PERSISTENT, BOOL}},
    {"ExperimentalMode", {PERSISTENT, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT, STRING}},
    {"GithubUsername", {PERSISTENT, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT, STRING}},
    {"GsmMetered", {PERSISTENT, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"IsMetric", {PERSISTENT, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LanguageSetting", {PERSISTENT, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    // TODO: rename the Live* learner cache keys to match their Cereal services, with migration for persisted values.
    {"LiveDelay", {PERSISTENT, BYTES}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ChestnutBranch", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ChestnutModelError", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ChestnutNotDetected", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ChestnutOverheated", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ChestnutPcieUnavailable", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ChestnutUpdateFailed", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ChestnutUsbSlow", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Pairing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_DriverMonitoringUncertain", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"DriveStateSession", {CLEAR_ON_MANAGER_START | DONT_LOG, JSON}},
    {"DriveStateRequest", {CLEAR_ON_MANAGER_START | DONT_LOG, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT, BOOL, "1"}},
    {"Offset1", {PERSISTENT, FLOAT, "0.0"}},
    {"Offset2", {PERSISTENT, FLOAT, "0.0"}},
    {"Offset3", {PERSISTENT, FLOAT, "0.0"}},
    {"Offset4", {PERSISTENT, FLOAT, "0.0"}},
    {"Offset5", {PERSISTENT, FLOAT, "0.0"}},
    {"Offset6", {PERSISTENT, FLOAT, "0.0"}},
    {"Offset7", {PERSISTENT, FLOAT, "0.0"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PairingEmail", {PERSISTENT, STRING}},
    {"ConnectProvider", {PERSISTENT, STRING, "comma"}},
    {"PairingProvider", {PERSISTENT, STRING}},
    {"PedalsOnUI", {PERSISTENT, BOOL, "0"}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RainbowPath", {PERSISTENT, BOOL, "0"}},
    {"RecordAudio", {PERSISTENT, BOOL}},
    {"RecordFront", {PERSISTENT, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"ShowBrakeStatus", {PERSISTENT, BOOL, "0"}},
    {"HideDMIcon", {PERSISTENT, BOOL, "0"}},
    {"ShowSpeedLimits", {PERSISTENT, BOOL, "0"}},
    {"SLCConfirmation", {PERSISTENT, BOOL, "0"}},
    {"SLCConfirmationHigher", {PERSISTENT, BOOL, "0"}},
    {"SLCConfirmationLower", {PERSISTENT, BOOL, "0"}},
    {"SLCFallback", {PERSISTENT, INT, "2"}},
    {"SLCOverride", {PERSISTENT, INT, "1"}},
    {"SLCQualifiedHistory", {PERSISTENT, JSON}},
    {"ConditionalModeConfig", {PERSISTENT | DONT_LOG, JSON}},
    {"ConditionalManualState", {PERSISTENT | DONT_LOG, JSON}},
    {"VehicleSelection", {PERSISTENT | DONT_LOG, JSON}},
    {"SafeMode", {PERSISTENT | DONT_LOG, BOOL, "0"}},
    {"CurveSpeedController", {PERSISTENT | DONT_LOG, BOOL, "0"}},
    {"CurveSpeedControllerNoLead", {PERSISTENT | DONT_LOG, BOOL, "0"}},
    {"ShowCSCStatus", {PERSISTENT | DONT_LOG, BOOL, "0"}},
    {"CurvatureData", {PERSISTENT | DONT_LOG, JSON}},
    {"CurveComfortData", {PERSISTENT | DONT_LOG, JSON}},
    {"SLCOffsetSchedule", {PERSISTENT | DONT_LOG, JSON}},
    {"MapdShadowEnabled", {PERSISTENT | DONT_LOG, BOOL, "0"}},
    {"OffroadPowerPreferences", {PERSISTENT | DONT_LOG, JSON}},
    {"SentryMotionPreferences", {PERSISTENT | DONT_LOG, JSON}},
    {"VASMPreferences", {PERSISTENT | DONT_LOG, JSON}},
    {"LaneChangePreferences", {PERSISTENT | DONT_LOG, JSON}},
    {"SLCPriority1", {PERSISTENT, STRING, "Dashboard"}},
    {"SLCPriority2", {PERSISTENT, STRING, "Map Data"}},
    {"SpeedLimitController", {PERSISTENT, BOOL, "0"}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT, BOOL}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAutomaticDownloads", {PERSISTENT, BOOL}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"ChestnutActive", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"ChestnutLoading", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION | CLEAR_ON_IGNITION_ON, BOOL}},
    {"Version", {PERSISTENT, STRING}},
};
